name: Generate

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Update Submodule
        run: |
          git submodule update --remote 

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Generate
        run: |
          make init
          make api
          go mod tidy

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: hominsu
          commit_user_email: hominsu@foxmail.com
          commit_author: Author <hominsu@foxmail.com>
